steps:
  # GCB only fetches a source archive, but the build requires an actual git repo. Note that the
  # clone behavior changed multiple times between 2017 and 2019 and might not be stable.
  # See: https://github.com/GoogleCloudPlatform/cloud-builders/issues/236#issuecomment-558991730
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git init
        git remote add origin https://github.com/getsentry/$REPO_NAME.git
        git fetch --depth=1 origin $COMMIT_SHA
        git reset --hard FETCH_HEAD
        git config -f .gitmodules submodule.core.url https://github.com/getsentry/$REPO_NAME.git

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull us.gcr.io/$PROJECT_ID/relay:nightly || true"
      ]

  # Pull the image with the first build stage
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull us.gcr.io/$PROJECT_ID/relay:deps || true"
      ]

  # Build the first stage
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--target", "relay-deps",
        "-t", "us.gcr.io/$PROJECT_ID/relay:deps",
        "--cache-from", "us.gcr.io/$PROJECT_ID/relay:deps",
        ".",
      ]

    # Build everything
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "us.gcr.io/$PROJECT_ID/relay:nightly",
        "-t", "us.gcr.io/$PROJECT_ID/relay:$COMMIT_SHA",
        "--cache-from", "us.gcr.io/$PROJECT_ID/relay:deps",
        "--cache-from", "us.gcr.io/$PROJECT_ID/relay:nightly",
        ".",
      ]

  # Trigger tests that depend on the Docker build
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    secretEnv: ['GH_TOKEN']
    args:
      - "-c"
      - |
        curl -u $$GH_TOKEN \
          -X POST -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/armenzg/relay/actions/workflows/integration.yml/dispatches \
          -d '{"ref": "armenzg/test-gcb-workflow-dispatch"}'

timeout: 3600s
options:
  # Run on bigger machines
  machineType: 'N1_HIGHCPU_8'
availableSecrets:
  secretManager:
  - versionName: projects/sentry-dev-tooling/secrets/RelayCIToken/versions/1
    env: 'GH_TOKEN'
# We can't have this in my fork
# secrets:
# - kmsKeyName: projects/sentryio/locations/global/keyRings/service-credentials/cryptoKeys/cloudbuild
#   secretEnv:
#     # This is a personal access token for the sentrybuilder account, encrypted using the
#     # short guide at http://bit.ly/2Pg6uw9
#     DOCKER_PASSWORD: |
#       CiQAE8gN7y3OMxn+a1kofmK4Bi8jQZtdRFj2lYYwaZHVeIIBUzMSTQA9tvn8XCv2vqj6u8CHoeSP
#       TVW9pLvSCorKoeNtOp0eb+6V1yNJW/+JC07DNO1KLbTbodbuza6jKJHU5xeAJ4kGQI78UY5Vu1Gp
#       QcMK
