name: After-GCB

on: workflow_dispatch

jobs:
  hello_world:
    name: Trigger after GCB build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run Rustfmt
        run: |
          echo "Hello world!"
